artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  file_name: SupplyChain.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/SupplyChain.csv

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv