models:

  Logistic Regression:
    C: [0.5, 1, 5]
    solver: ['liblinear', 'lbfgs', 'newton-cg']
    penalty: ['l2']
    class_weight: [{0: 1, 1: 5}, {0: 1, 1: 10}]
    max_iter: [5000]

  SVM:
    C: [0.5, 1, 10]
    kernel: ['rbf', 'poly']
    gamma: ['scale', 'auto']